### ISSUE TITLE
[dim] fix sqlalchemy usage to produce statements which work with stricter MySQL sql_mode

### ISSUE THREAD

**Issue by miesi** [1and1/dim#10]
target sql mode
```
sql_mode                                 = 'REAL_AS_FLOAT,PIPES_AS_CONCAT,ANSI_QUOTES,IGNORE_SPACE,ONLY_FULL_GROUP_BY,ANSI,STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
```

**Comment by miesi** [comment]
def output_list(
.outerjoin(Output.updates).group_by(*Output.__table__.columns)

**Comment by miesi** [comment]
def zone_list (`ndcli list zones`
        if fields:
            views_stmt = db.session.query(ZoneView.zone_id, func.count('*').label('views')).group_by(ZoneView.zone_id).subquery()
            qfields.append(views_stmt.c.views)
            groups_stmt = db.session.query(Zone.id.label('zone_id'), ZoneView.id, func.count('*').label('zone_groups'))\
                .join(ZoneView)\
                .join(ZoneGroup, ZoneView.groups)\
                .group_by(Zone.id).subquery()

**Comment by miesi** [comment]
def zone_list2
 if fields:
            views_stmt = db.session.query(ZoneView.zone_id, func.count('*').label('views')).group_by(ZoneView.zone_id).subquery()
            qfields.append(views_stmt.c.views)
            groups_stmt = db.session.query(Zone.id.label('zone_id'), ZoneView.id, func.count('*').label('zone_groups')) \
                .join(ZoneView) \
                .join(ZoneGroup, ZoneView.groups) \
                .group_by(Zone.id).subquery()
            qfields.append(func.coalesce(groups_stmt.c.zone_groups, 0).label('zone_groups'))

**Comment by miesi** [comment]
def zone_list_views
        if fields:
            qfields.extend(self._zone_view_rights())
        views = db.session.query(ZoneView.name, *qfields).filter_by(zone=zone).group_by(ZoneView.name).order_by(ZoneView.name)

**Comment by Srudush** [comment]
The cases for zone_list_views and zone_list2 can't be reproduced with ndcli. Would be good to have actual commands to reproduce the issues to fix them. From a short look I couldn't find any problems.
