### ISSUE TITLE
Can not find python3-dimclient rpm

### ISSUE THREAD

**Issue by emayoral** [1and1/dim#112]
Can not find anywhere python3-dimclient rpm required by python3-ndcli-4.0.1-1.el8.x86_64.rpm

Would like to have ndcli installed in a centos 8 (rocky 8 , actually) host.

.github/workflows/release_dimclient.yml suggests it should be part of the release, but it is not there.

$ sudo dnf install python3-ndcli-4.0.1-1.el8.x86_64.rpm
Last metadata expiration check: 2:59:04 ago on mié 29 sep 2021 04:54:50 UTC.
Error: 
 Problem: conflicting requests
  - nothing provides python3-dimclient needed by python3-ndcli-4.0.1-1.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

**Comment by TheMeier** [comment]
dimclient is in the directory https://github.com/1and1/dim/tree/master/dimclient with its own setup.py

**Comment by emayoral** [comment]
Yes. But because of how RPM works, if I install it via setup.py RPM will still be unaware that dimclient is present in the system, and it will still complain about "nothing provides python3-dimclient".

If the release includes a package python3-ndcli-4.0.1-1.el8.x86_64.rpm , which requires python3-dimclient , and no system package provides it (which is expected), then another package should be included in the release which provides  python3-dimclient .

Otherwise, python3-ndcli-4.0.1-1.el8.x86_64.rpm is not installable (unless you resort to --skin-broken or --nodeps , which is absolutelly not recommended).

Also .github/workflows/release_dimclient.yml suggests that a python3-dimclient RPM is build, but for some reason has not been released. Maybe failed RPM build?

**Comment by Srudush** [comment]
It was release some time ago with tag [0.4.3](https://github.com/1and1/dim/releases/tag/dimclient-0.4.3).

**Comment by emayoral** [comment]
You are right! Thank you very much!
