### ISSUE TITLE
[L3D] ndcli modify container set layer3domain

### ISSUE THREAD

**Issue by miesi** [1and1/dim#124]
```
ndcli modify container <C> set layer3domain <D>
```

**Comment by Srudush** [comment]
I don't think that will work. Imagine the following setup:

```
ndcli create layer3domain foo
ndcli create layer3domain bar
ndcli create layer3domain charlie
ndcli create container 192.168.0.0/16 layer3domain foo
ndcli create container 192.168.0.0/16 layer3domain bar
```

When issuing the command `ndcli modify container 192.168.0.0/16 set layer3domain charlie`, which of the two containers should be moved to container charlie?

Maybe we can use something like

```
ndcli modify container 192.168.0.0/16 layer3domain foo move to layer3domain charlie
```

**Comment by miesi** [comment]
```
ndcli modify container 192.168.0.0/16 layer3domain foo move to charlie
```

**Comment by miesi** [comment]
Please also update `static` childs of container.

subnets of pools and their static/reserved children of subnets are *not* moved when their parent container is moved. See #123 for moving pools to another layer3domain
