### ISSUE TITLE
pool owning-user-group can be set but not unset

### ISSUE THREAD

**Issue by miesi** [1and1/dim#138]
owning user-group of a pool can be set but not unset.
```
ndcli modify pool p owning-user-group g
```
I'd like to propose to move owning-user-group to set/remove
```
ndcli modify pool p set owning-user-group g

ndcli modify pool p remove owning-user-group g
```

**Comment by miesi** [comment]
check if empty handling is implemented like for ttl.

**Comment by zeromind** [comment]
There's already special handing for TTL to unset it: [ndcli/dimcli/__init__.py#L607](https://github.com/1and1/dim/blob/f8167e1d7c5a84ba82c2ec5cef5fddb3e620fa3b/ndcli/dimcli/__init__.py#L620)
