### ISSUE TITLE
move login_prompt from dim client lib to ndcli

### ISSUE THREAD

**Issue by miesi** [1and1/dim#182]
remove interactive parts from dimclient lib.

move login_prompt from dim client lib to ndcli, so interactive stuff is only in ndcli.

in the past people got confused by so many options how to connect. Sometimes they forgot to set the username because it worked as long as the cookie was valid.

update dim/doc/dimclient.rst

**Comment by Srudush** [comment]
login_prompt is moved in #208 into ndcli, but not yet deprecated in dimclient. So when #208 is merged, we can close this, I think.

**Comment by Srudush** [comment]
Was released with 5.0
