### ISSUE TITLE
make ndcli modify pool <p> set layer3domain <l3d> possible for pools with subnets smaller /24

### ISSUE THREAD

**Issue by miesi** [1and1/dim#233]
```
$ ndcli modify pool ic-documentation-only-5 set layer3domain 6724-global 
ERROR - The view default of the zone 13.214.85.in-addr.arpa is not empty.

$ ndcli list pool ic-documentation-only-5
prio subnet         gateway free total
   1 85.214.13.0/26           58    64
INFO - Total free IPs: 58

  85.214.13.0/26 (Subnet) pool:ic-documentation-only-5
  85.214.13.64/28 (Subnet) pool:de-ber-rs1-gsp-public-2052
  85.214.13.80/28 (Subnet) pool:de-ber-rs2-gsp-public-2052
  85.214.13.96/29 (Subnet) pool:de-ber-rs-dns-public-304-live
```
This happens because the code tries to delete the reverse zone although the zone is not yet empty.

I suggest to ignore errors returned by
```
1331             self._delete_reverse_zones(subnet, force=False)
```
when admin is moving subsequent pools (e.g. `de-ber-rs1-gsp-public-2052` ...) the reverse zone will get emptied. Last pool will then be able to delete reverse zone.

**Comment by Srudush** [comment]
It is weird that the error returns, that the zone is not empty.
In https://github.com/1and1/dim/blob/master/dim/dim/rpc.py#L3096-L3105 there is special handling in place for ipv4 networks to check that the view is completely empty.
