### ISSUE TITLE
Fix or create RPM packages for OpenSUSE

### ISSUE THREAD

**Issue by jlalvarez-arsys** [1and1/dim#271]
Trying to install the FC37 package on opensuse will break because it looks for the package `python311-dns` but this package is called `python311-dnspython` on OpenSUSE.

Adding a dependency to install either `python311-dns` or `python311-dnspython` or making an RPM package for OpenSUSE would fix the issue.

In the meantime, installing `ndcli` and `dimclient` with a broken dependency then installing `python311-dnspython` separately works fine.

**Comment by zeromind** [comment]
The "new" packages for `dimclient` and `ndcli` are available here: https://build.opensuse.org/project/show/home:zeromind:dim
